### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\%blah\\AppData\\Local\\Temp\\tmpaqaf567o.html'

### ISSUE THREAD

**Issue by mechengmaster** [vincentropy/python_cartography_tutorial#1]
Working through this tutorial when I call the following function at In [7]:

```python
go_arrivals_frame(1, 8.5, "frames")
```

I receive the following access error:
```python
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-25-4bf96916e65c> in <module>()
      1 # Next, we generate a sequence of these frames that we can stitch together into a movie.
      2 # We can then call our function in a loop to generate many frames.
----> 3 go_arrivals_frame(1, 8.5, "frames")

<ipython-input-23-142d1bd51dc2> in go_arrivals_frame(i, hour_of_day, save_path)
     11 
     12     # generate the png file as a byte array
---> 13     png = my_frame._to_png()
     14 
     15     #  now add a caption to the image to indicate the time-of-day.

C:\ProgramData\Anaconda3\lib\site-packages\folium\map.py in _to_png(self)
    259             with tempfile.NamedTemporaryFile(suffix='.html') as f:
    260                 fname = f.name
--> 261                 self.save(fname, close_file=False)
    262                 driver = selenium.webdriver.PhantomJS(
    263                     service_log_path=os.path.devnull

C:\ProgramData\Anaconda3\lib\site-packages\branca\element.py in save(self, outfile, close_file, **kwargs)
    154         """
    155         if isinstance(outfile, text_type) or isinstance(outfile, binary_type):
--> 156             fid = open(outfile, 'wb')
    157         else:
    158             fid = outfile

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\tom_g\\AppData\\Local\\Temp\\tmpaqaf567o.html'
```

I am using a Jupyter Notebook on Windows 10.  Can you help me fix the issue please?

**Comment by vincentropy** [comment]
The _to_png() call uses Phantom JS to render the HTML and record a PNG.

It looks like ~~Phantom JS~~ folium is trying to write in a folder on your computer where you do not have write permission. in this case `C:\\Users\\tom_g\\AppData\\Local\\Temp\\tmpaqaf567o.html`

You could check if that folder exists and that you have write permission for it.

Hopefully that helps you in the right direction a bit… Let me know if you make any progress.

**Comment by mihalw28** [comment]
Have the same issue and stuck with it. I have tried to add new system 'path' but still get an error.

**Comment by vincentropy** [comment]
This error seems to originate [on this line in folium](https://github.com/python-visualization/folium/blob/0a8fdfc6f01dbacfdf56306ad164d77c2a9a4d2a/folium/folium.py#L304).

It may be related to the way they open the temporary file. I will try to have a look, but in the mean time, perhaps you could try to file an issue there as well.

**Comment by mihalw28** [comment]
I found kind of a discussion on __to_png()_  method, but I am a newbie and I can not pull valuable informations to deal with issue.
https://github.com/python-visualization/folium/pull/634

**Comment by vincentropy** [comment]
There have been a few changes to the way folium handles _to_png and the notebooks have been updated with the latest version of folium. Hopefully this resolves these issues, so I'm closing this for now.
