### ISSUE TITLE
In part3_animations.ipnb  generating frame crashes on missing phantomjs executable. 

### ISSUE THREAD

**Issue by iholas** [vincentropy/python_cartography_tutorial#3]
this line `go_arrivals_frame(1, 8.5, dir_name)` causes the following error: 
 

> /home/iholas/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py:49:`

 > UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
>   warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '

> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> ~/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/selenium/webdriver/common/service.py in start(self)
     75                                             stderr=self.log_file,
---> 76                                             stdin=PIPE)
     77         except TypeError:

> ~/anaconda3/envs/tf_gpu/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
 >   708                 if text_mode:
> --> 709                     self.stdin = io.TextIOWrapper(self.stdin, write_through=True,
>    710                             line_buffering=(bufsize == 1),

> ~/anaconda3/envs/tf_gpu/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
>    1343                 except ValueError:
> -> 1344                     exception_name = b'SubprocessError'
>    1345                     hex_errno = b'0'

> FileNotFoundError: [Errno 2] No such file or directory: 'phantomjs': 'phantomjs'

> During handling of the above exception, another exception occurred:

> WebDriverException                        Traceback (most recent call last)
> <ipython-input-14-0fb1259ad699> in <module>
> ----> 1 go_arrivals_frame(1, 8.5, dir_name)

> <ipython-input-11-fa32733fbdc6> in go_arrivals_frame(i, hour_of_day, save_path)
>       6 
>       7     # generate the png file as a byte array
> ----> 8     png = my_frame._to_png()
>       9 
>      10     #  now add a caption to the image to indicate the time-of-day.

> ~/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/folium/folium.py in _to_png(self, delay)
>     304 
>     305             driver = selenium.webdriver.PhantomJS(
> --> 306                 service_log_path=os.path.devnull
>     307             )
>     308             driver.get('about:blank')

> ~/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py in > __init__(self, executable_path, port, desired_capabilities, service_args, service_log_path)
>      54             service_args=service_args,
>      55             log_path=service_log_path)
> ---> 56         self.service.start()
>      57 
>      58         try:
> 
> ~/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/selenium/webdriver/common/service.py in start(self)
>      81                 raise WebDriverException(
>      82                     "'%s' executable needs to be in PATH. %s" % (
> ---> 83                         os.path.basename(self.path), self.start_error_message)
>      84                 )
>      85             elif err.errno == errno.EACCES:

> WebDriverException: Message: 'phantomjs' executable needs to be in PATH.

**Comment by PyMap** [comment]
Hi Vincent Lonij! I really enjoyed your previous work. I completed the tutorials 1° & 2° and I think that you have done a really nice job! 
I'm trying with the third one right now and I'm blocked with the "go_arrivals_frame" function. Even if I'm trying to use geckodriver as you suggested (I put the '.exe' file in the same folder where I have my jupyter notebook and followed the os.environ["PATH"] += os.pathsep + "." instruction). Anyway, when I run the function I get an error on this line:
png = my_frame._to_png()
The error I get is the following:
WebDriverException: Message: 'phantomjs' executable needs to be in PATH.
I have checked my PATH with os.getcwd() and I get the same address where I put the "geckodriver.exe"
I'm using a python 3.6 virtual environment on 2.7 root (I have windows10)
Do you have any idea about what could be happening?

**Comment by vincentropy** [comment]
Hey @iholas  and @PyMap. Sorry for the late response. If you're still experiencing this problem it most likely has something to do with the version of selenium you're using. The latest version of selenium no longer uses phantomjs so it should not be asking for that dependency. You can check which version you're using in python by running:

`import selenium`
`print(selenium.__version__)`

you should get 3.14 or greater. Let me know if that helps.

**Comment by PyMap** [comment]
Hey @vincentropy! Thanks for your comment. I don’t remember how I fixed it but I could make it works. Thanks again for your Job! https://link.medium.com/qEUdTMl7MZ

**Comment by vincentropy** [comment]
Thanks for the update @PyMap. Nice work in the Medium article :)

Closing this issue for now.
